# Generated by Django 5.1.6 on 2025-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0008_remove_booking_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
